[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "704b91213faf96a8e770ca9b50dddc9a44027ba9"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "76afd0c766f0ae9f3162d83fe0e839bcd50fd6d5e072cc6e96afb9eb863d2c8f"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.aarch64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "38f1d73780ae6a4e3fca372b0c3f2d67201cb255"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "99d57532e31da090f64738a68fff0a0668a1a18038608d70004fdfe845f2c738"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.aarch64-linux-musl.tar.gz"
[[Bzip2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "91655a4936f583092cb5d6097b52b3079d11cc3a"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "e4516a2abb2cb65908740df4535af3c6c621fb924edeb4beea43ecceadd3bbb0"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.armv7l-linux-gnueabihf.tar.gz"
[[Bzip2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cf422ab83f4afbd0e119a343a1746c8911caa5d"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "f46187c648aec6fb128e24d8708714326bbd850a54963991cae241ad2eeb6654"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.armv7l-linux-musleabihf.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "04533670c290e877af64d4fc895eaefe5d223b96"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "ce99922f7b45a3691c73aac19cc0e520c152004ff3f50844f3d78b028395986e"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.i686-linux-gnu.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "524eadfa5dbd15ea8d3fa676178b70d05c8620fb"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "d8aeff04efd0186c7720f8c9417c007f50ff8c270bf93e4ec30259caef44db59"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.i686-linux-musl.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "336ae3e69ea75b92d9b8d056f4a5d77c84547ef1"
os = "windows"

    [[Bzip2.download]]
    sha256 = "56a9283c4aa978049b199dd3008561fd55bab1e3d2affcc10a8112fc383ee962"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.i686-w64-mingw32.tar.gz"
[[Bzip2]]
arch = "powerpc64le"
git-tree-sha1 = "03951454e7bc84ece6991740e48ee9ff157b5fcd"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "89bd9b7d3b72749403b7369459b5262799b409b26f465239ef976ae981f47729"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.powerpc64le-linux-gnu.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "090d5bbc0cd00bc904095c45fffc2714733e8cfd"
os = "macos"

    [[Bzip2.download]]
    sha256 = "49dd209f412005744e8ffdcbdc6b4b3510806b758d65b09404d1933175a0236b"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.x86_64-apple-darwin.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "dd9f894a54661b81fd9ac24e96c5bd0b393b348f"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "191f8d4c9e7879f1723cce3d685a2dea2382ff141d5c15db99723b366a6657e5"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.x86_64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "3312529f0d5dfcca5bbf7e21972467924a0344aa"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "2a2701fbf602228e53dcba49f2b0caf04c2111d4d6e1d5f8631415e283fc7fd6"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.x86_64-linux-musl.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "eadf42b2455bf49d7802b6114d0e12d3e767b94d"
os = "freebsd"

    [[Bzip2.download]]
    sha256 = "a184046789d34af8e19cc899325b424a761e9492443f31bae2c99e4f87b21b9e"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.x86_64-unknown-freebsd.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "f0beacd1cc3af09bfe70c9b7ffd2ca6a4dbb15eb"
os = "windows"

    [[Bzip2.download]]
    sha256 = "12d099023885ff53ffc1ad29690945c7a70a99e2e71375c178d95adb86e098f4"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.7+0/Bzip2.v1.0.7.x86_64-w64-mingw32.tar.gz"
