[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "4c5023e38c584addc80a62c9aa0df52b16906e04"
os = "macos"

    [[Bzip2.download]]
    sha256 = "f6d50b7ba821f09868df6da62a6916f53a931ef53643eba567ef027a025ecb54"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.aarch64-apple-darwin.tar.gz"
[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "3119ca909a128d04d29084cdc9fe7c2fd85a123e"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "05c0a69d1f0c4dd5b4e08a2bf1b5d05966912f42985231e346c6ccd9c6223ad9"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.aarch64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "466bcd43544049d9610b0e62266b489629554e6e"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "222820724f834ffaf8cc7724eb4fe20c00b50289f49fd5c6239431f7c626e209"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.aarch64-linux-musl.tar.gz"
[[Bzip2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f9c2fb3842f0d4546c020e50b91d757a1a16e97"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "cffc8bf8dc01bdf9011690a8cb0852f35225d50783d29cbf9853f18cbb7857d0"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.armv6l-linux-gnueabihf.tar.gz"
[[Bzip2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "46601c5c474fce4db19c6b375492f9452c634dc0"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "391c5504f4e61d9f88791ddd80f4b59bf5556fa9bebc5c626a5beefd8ad971e7"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.armv6l-linux-musleabihf.tar.gz"
[[Bzip2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08f19d9746fdef1ab522f36a9ae8d9fcb98d555e"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "49e8d6ed599d84695f47f86357e897ab5a858825efa04cac811f6894cdac9343"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.armv7l-linux-gnueabihf.tar.gz"
[[Bzip2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bd9994568c2d4e8d22334d0a4cef32ec2ff51f2b"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "2a37b32746a081f4e4461dc0272d3ddc715425fc8ee7847c7b074c616fe1b252"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.armv7l-linux-musleabihf.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "6ced42be4f4d109d2fe4e1873d8d889c53272b97"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "07296459321fbb58a772cc6fe8236168549510b85c305e6d07bb0315f1ce9264"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.i686-linux-gnu.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "7106e0c67596de846e8a91e1540d7b11fac4a986"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "437f665f1e1bcc37f173d72728deefa2a63b71b297db4f30bdc4e42bf85b8d2d"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.i686-linux-musl.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "8a8f0afb8b823712703ed778719b7f72ec1ff724"
os = "windows"

    [[Bzip2.download]]
    sha256 = "47756835d300b482ed2110521c58ff76cf8a7068dd03bfb77896e25172dcdea3"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.i686-w64-mingw32.tar.gz"
[[Bzip2]]
arch = "powerpc64le"
git-tree-sha1 = "3c22ef3937b2a37971ae3929a8e2da4c1f98338c"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "bb0ac9202f2626ed54f08dd30b16b3afe042bd7a1ed34ba65f24980bf1270361"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.powerpc64le-linux-gnu.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "225b8f54f1349d250acc02bc7f6a60cfaa6bdf82"
os = "macos"

    [[Bzip2.download]]
    sha256 = "0f64918b90502929252b4bf3402aa1d863f1bc0b4a89b622809670280934954c"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.x86_64-apple-darwin.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "d681016bd049307ae27ae897e0b256be7296aecb"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "66ab5f13291739ee439e7b7a44f9c7ef16dcab2cbfa60e82dc9e2904b1f3549e"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.x86_64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "5d33cb5f86e4100656e5b9594106dd5f1c633034"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "6d144fdd57e1fa289258ddb3bd76086e1545fd30cf21e5870d2d548755551eb1"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.x86_64-linux-musl.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "d84d10d7b570774ecfa352d8f1d9740a104ab7a7"
os = "freebsd"

    [[Bzip2.download]]
    sha256 = "5f3d13c4adf64944b31adea00232f4c4f5bc32b0b3a2af50d6208f5fac3f087d"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.x86_64-unknown-freebsd.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "d2a35680da3d58989f9dfd0bfba83d68a793346b"
os = "windows"

    [[Bzip2.download]]
    sha256 = "84fac35d7e61e1f851f7b857726bd07ddb8aab05e9067010ef3a468a306438f0"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+0/Bzip2.v1.0.8.x86_64-w64-mingw32.tar.gz"
