[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "73674ecf50f470c8706f958c9b6b1c5f2106ad71"
os = "macos"

    [[Bzip2.download]]
    sha256 = "9395374a28451bc4edc2ae404dbf2a6b833780919bd1544cb3224a59ffd55288"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.aarch64-apple-darwin.tar.gz"
[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "fe7e4dfe9b699a6d931ad9f3bf4545ed7393a197"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "258ff06f62c91b85793bdba74d03a8e62bc943797fdb93d90b96728f23b74e0f"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.aarch64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "bc1850caab2120fedd7c2db8aba8f8546737702a"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "1482c85b9b2091720ec1f035b1a50e9f76dc88ce506e7f57ed2e7a04eb6aee1d"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.aarch64-linux-musl.tar.gz"
[[Bzip2]]
arch = "aarch64"
git-tree-sha1 = "5fe793fdcac60482e71441548436f6da91568e2e"
os = "freebsd"

    [[Bzip2.download]]
    sha256 = "3287783fafda14af2522b9af91a9f7903c06e399fb984fcbc33e172721423800"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.aarch64-unknown-freebsd.tar.gz"
[[Bzip2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a1b4faf97f40e00a3651df10c540ef12dee6109d"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "b33a6af1ff7c93d2be97a569dacf0e38f1f8da90221b8e9b14d868bbe7d4868a"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.armv6l-linux-gnueabihf.tar.gz"
[[Bzip2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a19fa94921ed9d20cc194d35007a56670fcf7cf7"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "7b7176461483390d59b0561224a09f28385a76769004d071e512126d5aa8d94c"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.armv6l-linux-musleabihf.tar.gz"
[[Bzip2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c5ef200dc7a9b6dc2a16459a846682981872252"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "5be0141cfcb54ea8ab2a73cca3b4e00a7cf0ed98e412a4ca1eab924f86ea5607"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.armv7l-linux-gnueabihf.tar.gz"
[[Bzip2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a14c21c5687bbfc468edd2322c0d6702683c51bd"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "df5ad91f96eb93ce273eaca1fc55572a15495009129251a466eee25c3f4b3dda"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.armv7l-linux-musleabihf.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "466c5fed79c00766bf7fe434b77b10cd00afb5a9"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "ce2e312181fda9ef3e437763745f15ad1a3dea78dc60a1a52aa1c922af24f7f0"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.i686-linux-gnu.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "d16052c13a7e8e77f9c69b02b038f0120a3d31cd"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "42e3ee10768865bc816685e643edc107bba9b4dcc6c8fd0cae529f9e78f58764"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.i686-linux-musl.tar.gz"
[[Bzip2]]
arch = "i686"
git-tree-sha1 = "51e16c5c28998820e4c8610d262c60714f275490"
os = "windows"

    [[Bzip2.download]]
    sha256 = "34b45ae0a3a55466579d405a6ebbd0795f453359d4a0728fdbe9ec3c9e218a1a"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.i686-w64-mingw32.tar.gz"
[[Bzip2]]
arch = "powerpc64le"
git-tree-sha1 = "f6d2ccafde0719b738f76924ddfa82ba63071d5d"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "3f089939eb6963d529223f9dfaa6a42c365540909959dd0eb0f9f3c82c3bc8de"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.powerpc64le-linux-gnu.tar.gz"
[[Bzip2]]
arch = "riscv64"
git-tree-sha1 = "87c6d3997903d9322459dd23a5942e6417e3a9b7"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "67e0551da2b81672a3fb04d9286285947dc893cec8c1c2f9b05330b8b496afe9"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.riscv64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "c017125e2d4d5164da672d43ed7bc53af6f711e4"
os = "macos"

    [[Bzip2.download]]
    sha256 = "89c4d79e52d2c2aeaa46c17c6e6fdca76177b0da156b94f20cfd64846347ba6a"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.x86_64-apple-darwin.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "400170e094faf2f95c44cd146a8ecea088b86fa1"
libc = "glibc"
os = "linux"

    [[Bzip2.download]]
    sha256 = "c9d2ec1268d0586b78b8c0afb2aca59860936c416f395dd290e8f2e96286aaca"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.x86_64-linux-gnu.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "d90c1dfd7cc840234df397dd130a590e6b94cb37"
libc = "musl"
os = "linux"

    [[Bzip2.download]]
    sha256 = "2c5777a4250cd11eff2f47b3aba48d46872da26100fcb346507338532626b966"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.x86_64-linux-musl.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "e059077c3a31c9ebdf6f2b4d8fbf34002a31e887"
os = "freebsd"

    [[Bzip2.download]]
    sha256 = "cf8e3520795ae782783368f12d9e02936305789f8ff904519b78da9fd3987f6a"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.x86_64-unknown-freebsd.tar.gz"
[[Bzip2]]
arch = "x86_64"
git-tree-sha1 = "e8c8d9b0791935aeeea18a3c8a2d6051bee92bad"
os = "windows"

    [[Bzip2.download]]
    sha256 = "e9b96cf17e05111abf2958ea2cacad62d48f31e105598b23f4881602b51892e9"
    url = "https://github.com/JuliaBinaryWrappers/Bzip2_jll.jl/releases/download/Bzip2-v1.0.8+3/Bzip2.v1.0.8.x86_64-w64-mingw32.tar.gz"
